version: '3.8'

services:
  myapiserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    #command: python myapiserver/server.pyc
    command: python -m myapiserver.server